version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  db-inserter:
    lang: node12
    handler: ./db-inserter
    image: ${DOCKER_USER:-alexellis2}/db-inserter:0.2.3
    annotations:
      topic: "drone-position/"
    environment:
      db_port: 5432
      db_name: postgres
    secrets:
      - db

  db-reader:
    lang: node12
    handler: ./db-reader
    image: ${DOCKER_USER:-alexellis2}/db-reader:latest
    secrets:
      - db

  # Microservice to render static HTML
  render-map:
    lang: node12
    handler: ./render-map
    image: ${DOCKER_USER:-alexellis2}/render-map:latest
    environment:
      datasource: "http://gateway.openfaas:8080/function/db-reader"
