version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  db-inserter:
    lang: node12
    handler: ./db-inserter
    image: ${DOCKER_USER:-alexellis2}/db-inserter:0.2.7
    annotations:
      topic: "drone-position/"
    environment:
      db_port: 5432
      db_name: postgres
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 5
    secrets:
      - db

  db-reader:
    lang: node12
    handler: ./db-reader
    image: ${DOCKER_USER:-alexellis2}/db-reader:0.1.6
    environment:
      db_port: 5432
      db_name: postgres
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 5
    secrets:
      - db
    
  # Microservice to render static HTML
  render-map:
    lang: dockerfile
    handler: ./render-map
    image: ${DOCKER_USER:-alexellis2}/render-map:0.1.0
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
