apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        name: pgadmin
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "pgadmin.fullname" . }}-password
              key: password
        - name: PGADMIN_PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
