apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgadmin.fullname" . }}-password
  labels:
    app: {{ template "pgadmin.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ default (randAlphaNum 10) .Values.password | b64enc | quote }}
