apiVersion: v1
kind: Service
metadata:
  name: emitter
  namespace: openfaas
spec:
  type: ClusterIP
  selector:
    app: broker
    namespace: openfaas
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8443
      targetPort: 8443
      name: https
